### PR TITLE
Update gradle and dependencies to latest of everything.

### PR DESCRIPTION
**Pull request by IgorGanapolsky**
Update kotlin, libraries, and gradle.

### CODE REVIEW

**Review by Serchinastico — APPROVED** [review]
Awesome! Thank you for your contribution!

**Review by Serchinastico — COMMENTED** [review]
I'm afraid the update to the new version of ktlint makes some of the project code outdated with the new guidelines, I will take a look tonight to fix them and merge the branch

**Comment by IgorGanapolsky** [comment]
@Serchinastico ktlint 0.15.1 still works

**Comment by Serchinastico** [comment]
It's fine, I created #3 fixing the linting issues while keeping you as the original author. I'm closing this PR and merging the other one with your changes. Yet again, thank you very much for your time and code!

**Pull request closed without merging**
